name: 'Django Migration Checker'
description: 'check Django app migrations dependency tree'
branding:
  icon: 'play'  
  color: 'blue'

inputs:
  app-path:
    description: 'app folder path'
    required: true
    default: 'app'

  docker-image:
    description: 'docker image name'
    default: 'hardcoretech/django-migration-checker'

  docker-image-tag:
    description: 'docker image tag of django-migration-checker'
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Run
      shell: bash
      run: |
        docker run --rm \
           --volume ${PWD}:/workspace \
           --workdir /workspace \
           ${{ inputs.docker-image }}:${{ inputs.docker-image-tag }} \
           ${{ inputs.app-path }}
