name: 'Django Migration Checker'
description: 'check Django app migrations dependency tree'
branding:
  icon: 'play'  
  color: 'blue'

inputs:
  app-path:
    description: 'app folder path'
    required: true
    default: 'app'

runs:
  using: docker
  image: Dockerfile
  env: 
    APP_PATH: ${{ inputs.app-path }}
